In [1]:

import pandas as pd

In [6]:
df = pd.read_pickle(r"C:\Users\matou\PycharmProjects\projects\streamlit\jobs_df.pkl")

In [9]:
df[-30:]

,title,link,date_of_scraping,skills,pay
198,Vývojář automatických testů (Embedded software...,https://jobs.techloop.io/job/23345,2023-05-06,"python,git",Salary hidden by company
199,Ansible Automation Engineer (Backup) - Senior ...,https://jobs.techloop.io/job/23140,2023-05-06,"python,git,sql,jira",Salary hidden by company
200,Linux Specialist,https://jobs.techloop.io/job/22799,2023-05-06,"python,bash,sql",Salary hidden by company
201,BI Data Engineer,https://jobs.techloop.io/job/23019,2023-05-06,"python,sql",Salary hidden by company
202,Senior Python Developer – Market Risk in Brno,https://jobs.techloop.io/job/18327,2023-05-06,"git,pandas",Salary hidden by company
203,Robotic Process Automation Developer (RPA),https://jobs.techloop.io/job/13182,2023-05-06,git,Salary hidden by company
204,DEVOPS ENGINEER | Automotive,https://jobs.techloop.io/job/23476,2023-05-06,"python,git,jenkins,sql",Salary hidden by company
205,Elektro-systémový inženýr se zaměřením na SPACE,https://jobs.techloop.io/job/21768,2023-05-06,python,Salary hidden by company
206,Ethical hacker (m/f),https://jobs.techloop.io/job/8099,2023-05-06,"python,linux",Salary hidden by company
207,Artificial Intelligence Intern (part-time),https://jobs.techloop.io/job/23383,2023-05-06,scikit-learn,Salary hidden by company
208,Senior Software Test Engineer (m/ž),https://jobs.techloop.io/job/17899,2023-05-06,python,Salary hidden by company
209,SYSTÉMOVÝ SPECIALISTA - LINUX ve fajn kolektivu,https://jobs.techloop.io/job/23056,2023-05-06,linux,Salary hidden by company
210,Business Application Developer pro AI,https://jobs.techloop.io/job/21104,2023-05-06,python,Salary hidden by company
211,SW Requirement Manager Junior,https://jobs.techloop.io/job/23992,2023-05-06,"python,sql",Salary hidden by company
212,PYTHON vývojář - automatizované testy řídících...,https://jobs.techloop.io/job/19805,2023-05-06,python,Salary hidden by company
213,Cyber security engineer (m/f),https://jobs.techloop.io/job/5620,2023-05-06,python,Salary hidden by company
214,Test software inženýr,https://jobs.techloop.io/job/22444,2023-05-06,"python,jenkins",Salary hidden by company
215,PLC programátor jednoúčelových strojů a stroj....,https://jobs.techloop.io/job/19094,2023-05-06,python,Salary hidden by company
216,SW VÝVOJÁŘ (CMAKE/PYTHON),https://jobs.techloop.io/job/11103,2023-05-06,"python,git",Salary hidden by company
217,Vývojář softwaru pro měřící techniku,https://jobs.techloop.io/job/19104,2023-05-06,"python,sql",Salary hidden by company
218,Senior Site Reliability Engineer,https://jobs.techloop.io/job/22214,2023-05-06,"python,git,jenkins,bash,sql",Salary hidden by company
219,REACT VÝVOJÁŘ - medior - pro JEDNIČKU mezi mzd...,https://jobs.techloop.io/job/24105,2023-05-06,python,Salary hidden by company
220,Specialista Cybersecurity & Networks,https://jobs.techloop.io/job/24081,2023-05-06,"python,bash",Salary hidden by company
221,EMBEDDED C DEVELOPER | Zdravotnictví,https://jobs.techloop.io/job/21946,2023-05-06,"python,git",Salary hidden by company
222,SW Test Engineer,https://jobs.techloop.io/job/19177,2023-05-06,git,Salary hidden by company
223,System Engineer - Cloud Operations,https://jobs.techloop.io/job/16867,2023-05-06,"python,git,bash,linux,sql",Salary hidden by company
224,C+Go Developer,https://jobs.techloop.io/job/23834,2023-05-06,git,Salary hidden by company
225,Datový analytik/Datová analytička (Bioinformatik),https://jobs.techloop.io/job/23235,2023-05-06,"python,bash,linux",Salary hidden by company
226,SQA technický leader,https://jobs.techloop.io/job/17144,2023-05-06,python,Salary hidden by company
227,Softwarový inženýr,https://jobs.techloop.io/job/18804,2023-05-06,python,Salary hidden by company

In [ ]:
# 201	Test Automation engineer	https://jobs.techloop.io/job/23100	2023-05-06	python,git	Salary hidden by company

In [29]:
# 'python' in df.loc[0, 'skills']
possible_skills = ['python', 'git', 'pandas', 'pyspark', 'scikit-learn', 'jenkins', 'numpy', 'bash', 'linux', 'sql',
                   'sklearn', 'pytorch', 'tensorflow', 'keras', 'jira']
# counts = [df['skills'].apply(lambda x: skill in x).value_counts()[True] if df['skills'].apply(lambda x: skill in x).value_counts().size > 1 else 0  for skill in possible_skills]
# if else needed, because error on 0 count for a skill
counts = [xx[True] if (xx := df['skills'].apply(lambda x: skill in x).value_counts()).size > 1 else 0 for skill in possible_skills]
# df['skills'].apply(lambda x: 'python' in x)
counts

[182, 94, 5, 1, 2, 11, 3, 28, 49, 60, 0, 2, 2, 0, 12]

In [30]:
df['skills'].apply(lambda x: "git" in x).value_counts()

False    107
True      94
Name: skills, dtype: int64

In [34]:
xx = pd.Series({x: y for x,y in zip(possible_skills, counts)}).reset_index(name='count').sort_values(by=['count'], ascending=False)
xx

           index  count
0         python    182
1            git     94
9            sql     60
8          linux     49
7           bash     28
14          jira     12
5        jenkins     11
2         pandas      5
6          numpy      3
4   scikit-learn      2
11       pytorch      2
12    tensorflow      2
3        pyspark      1
10       sklearn      0
13         keras      0

In [70]:
df.iloc[:10]

,title,link,date_of_scraping,skills,pay
0,PYTHON DEVELOPER PRO ELEKTRONOVOU MIKROSKOPII,https://jobs.techloop.io/job/33848,2023-06-27,python,Salary hidden by company
1,Studentská stáž v Brně,https://jobs.techloop.io/job/33790,2023-06-26,"python,git",Salary hidden by company
2,Senior/medior backend vývojář cloud aplikací,https://jobs.techloop.io/job/33677,2023-06-26,"python,git,bash,sql",Monthly 52k ~ 70k CZK (Gross)
3,SQA Engineer / SW tester,https://jobs.techloop.io/job/33768,2023-06-26,python,Salary hidden by company
4,Hledáme studenty se zájmem o testování SW (Pyt...,https://jobs.techloop.io/job/33772,2023-06-26,python,Salary hidden by company
5,DevOps Engineer,https://jobs.techloop.io/job/33673,2023-06-26,"python,git,bash",Monthly 70k ~ 100k CZK (Gross)
6,IT Project Manager Junior with German,https://jobs.techloop.io/job/33340,2023-06-24,python,Salary hidden by company
7,RPA Developer,https://jobs.techloop.io/job/33077,2023-06-24,"python,git,sql",Salary hidden by company
8,BI Data Engineer,https://jobs.techloop.io/job/33482,2023-06-24,"python,sql",Salary hidden by company
9,Digitalization Engineer Junior – inovátor digi...,https://jobs.techloop.io/job/33252,2023-06-24,"python,git,sql",Salary hidden by company

In [4]:
dff = df.copy()
dff = dff.iloc[:6]
for x in dff.iterrows():
    print(x[0])
    if pd.isna(x[1].skills) or x[1].skills == '':
        dff.drop(x[0], inplace=True)
dff = dff.reset_index(drop=True)

0
1
2
3
4
5

In [5]:
for x in df.iterrows():
    if pd.isna(x[1].skills) or x[1].skills == '':
        print(x)

# to_remove = [x[0] for x in df.iterrows() if pd.isna(x[1].pay)]
# to_remove

In [46]:
df['skills'].value_counts()
df.iloc[df[df['pay'] == 'Monthly 1 ~ 1 CZK (Gross)'].index]

,title,link,date_of_scraping,skills,pay
24,IT Business Analyst,https://jobs.techloop.io/job/25006,2023-05-29,"python,git,sql",Monthly 1 ~ 1 CZK (Gross)

In [243]:
pd.isna(df.loc[0,'skills'])
pd.isnull(df.loc[0,'skills'])
df.loc[0,'skills'] == ''

False

In [245]:
df= pd.merge(df,dff, how='outer')
df['date_of_scraping'] = df['date_of_scraping'].astype('datetime64[D]')
df.sort_values(by=['date_of_scraping'], ascending=False, ignore_index=True, inplace=True)
df.drop_duplicates('link', keep='last', inplace=True)
df = df.reset_index(drop=True)
df

,title,link,date_of_scraping,skills
0,Python Backend Developer | Django (Praha/Brno),aaaaaaaaaaa,2023-05-08,"python,git,sql,sqlite,ml"
1,Python Backend Developer | Django (Praha/Brno),https://jobs.techloop.io/job/24269,2023-05-08,"python,git,sql,sqlite,ml"
2,Python Developer – Market Risk (mid/senior lev...,https://jobs.techloop.io/job/19922,2023-05-06,"git,pandas"
3,Firmware Developer / Vývojář FW,https://jobs.techloop.io/job/23188,2023-05-06,python
4,System Engineer - Cloud Operations,https://jobs.techloop.io/job/16867,2023-05-06,"python,git,bash,linux,sql"
...,...,...,...,...
72,Robotic Process Automation Developer (RPA),https://jobs.techloop.io/job/13182,2023-05-06,git
73,IT specialist / System Administrator,https://jobs.techloop.io/job/24015,2023-05-06,"python,linux,sql"
74,Software Test Engineer (m/ž),https://jobs.techloop.io/job/17900,2023-05-06,"python,git"
75,Specialista/ka datové analytiky - Data scientist,https://jobs.techloop.io/job/22651,2023-05-06,"python,pandas,numpy,sql,ml"
76,SW Test Engineer,https://jobs.techloop.io/job/19177,2023-05-06,git

In [246]:
for x in df.iterrows():
    print(x[0])
    print(x[1])
    print(x[1].title)
    print(type(x[1]))
    break

0
title               Python Backend Developer | Django (Praha/Brno)
link                                                   aaaaaaaaaaa
date_of_scraping                               2023-05-08 00:00:00
skills                                    python,git,sql,sqlite,ml
Name: 0, dtype: object
Python Backend Developer | Django (Praha/Brno)
<class 'pandas.core.series.Series'>

In [247]:
text = """<p class="MuiTypography-root MuiTypography-body1 css-1rlo451"><span>About “Data Strategy, Management &amp; Ethics” team
<p>The team is based in Prague and Brno and focuses on strategic consulting services in the topic of data. We design data strategies for global clients, build data implementation roadmaps, set overall data visions, help manage data (e.g. data governance, quality, MDM etc.), advise on the use of advanced analytics (e.g. ML, NLP etc.) and drive regulatory and ethical compliance (e.g. EU’s AI Act etc.). Being part of a wider ‘Digital Enablement’ area, we work closely with other teams focused on Big Data &amp; Data Science, Business Intelligence &amp; Reporting, as well as Digital Transformation and Software Development.</p>
About Manager
<p>Patrik is the team manager leading consulting services and being responsible for the Data Strategy, Management &amp; Ethics team. Patrik studied at University of Kent and dedicated his early career to development of analytics and business intelligence before transitioning to advisory roles. In recent years, Patrik worked with some of Europe's largest organisations: supported an Energy client in the Netherlands; advised a major Retailer in Sweden; and built a strategy for a smart city in Saudi Arabia. Patrik enjoys free time with his family and stays active trail running, and walking his dog Molly.</p>
Job description &amp; summary
<p>As a part of our “Data Strategy, Management &amp; Ethics” team you will:</p>
<ul>
<li>Develop custom Python code and solutions.</li>
<li>Continuously identify new solution concepts and innovations.</li>
<li>Develop and support already running solutions and tools both in Czechia and globally for internal and external clients.</li>
<li>Collaborate and interact with cross-functional project, business and development teams.</li>
<li>Operate in a focused team that will require a proactive and independent attitude.</li>
<li>Help shape and expand the current practice by introducing new technologies and approaches.</li>
<li>Share best practices and knowledge both internally and externally.</li>
<li>Requirement of the role</li>
<li>Minimum of 1-2 years of experience of development in Python.</li>
<li>Python programming skills and knowledge of Git.</li>
<li>Experience preferred with standard libraries like numpy, pandas, scikit-learn, requests, openpyxl, pyodbc and similar.</li>
<li>Open-minded and creative to try out new frameworks, tools and technologies.</li>
<li>Proactive in development of new concepts and solutions.</li>
<li>Able to work independently and interact with stakeholders across hierarchies.</li>
<li>Professionally fluent in English and preferred but not essential Czech or Slovak.</li>
</ul>
What we are offering
<ul>
<li>Stable and challenging working environment providing plenty of opportunities for your continuous professional growth.</li>
<li>Paid time off 25 days, 3 sick days and 1-2 extra days off at the end of the year.</li>
<li>High-end Ultrabook and iPhone with unlimited data.</li>
<li>Benefit program with 30.000 points that you can use for holidays, education, food vouchers, sports (Multisport), health... Simply on what you enjoy.</li>
<li>Big support for your education and development. Each employee has their own budget and your proactivity is highly welcomed.</li>
<li>After-work and team activities (team building, ski weekend, etc..)</li>
<li>You will develop your skills while having the support from the top notch professionals in the team (e.g. career coaching, etc).</li>
<li>Opportunity to work in the future at a foreign PwC office, for example in the USA, Canada and there are others in the selection.</li>
</ul>
<p>PwC is the largest audit team in the Czech Republic, law, tax, consulting and technology, data or forensic teams. Find out how easy it is to combine this knowledge when you're in the right place.</p>
<p>With us, you will get the opportunity to see how business is done in large companies. We are part of an international network of companies with more than 327,000 colleagues in 155 countries.</p>
<p>Once you've applied for a position, our recruiter for the Digital Enablement team will contact you . You'll then have an interview/selection process. If you're successful and you also get along with the hiring manager, you're good to go and start your career!</p></span></p>"""

In [248]:
text = str.lower(text)

In [249]:
possible_skills = ['python', 'git', 'pandas', 'scikit-learn', 'sklearn', 'jenkins', 'numpy', 'bash', 'linux', 'sql']
req_skills = [skill for skill in possible_skills if skill in text]
req_skills

['python', 'git', 'pandas', 'scikit-learn', 'numpy']

In [250]:
','.join(req_skills)

'python,git,pandas,scikit-learn,numpy'

In [251]:
out = ''
for skill in possible_skills:
    if skill in text:
        out += f',{skill}'
out

',python,git,pandas,scikit-learn,numpy'